### ISSUE TITLE
modify database code

### ISSUE THREAD

**Issue by chiaraumattino** [silviapanizzutti/ip-address#3]
Modify the database code (from moodle) for username and password. Add salt

**Comment by chiaraumattino** [comment]
NOT in ip-address. I added it the wrong position. Remove the database branch and do another one.

**Comment by jacopobre** [comment]
I have cancelled your branch "database" and created a new one called "pew-database" where you can work again 👍

**Comment by chiaraumattino** [comment]
Great! thanks Jacopo! Now I paste the prev code & start working to add the salt.

**Comment by chiaraumattino** [comment]
Salt is added and also other modifications to better fit the database with our project.
