### ISSUE TITLE
input on the main 

### ISSUE THREAD

**Issue by chiaraumattino** [silviapanizzutti/ip-address#4]
@silviapanizzutti please note the modifications I've done in my branch. 
Can you insert in the main the input() and the features in order to link it with the database as we agreed? 
I think it's better to add it in the main of my branch and merge it with your branch later.

**Comment by jacopobre** [comment]
@silviapanizzutti I have recently updated my module on the branch called map. Could you please link it with the main.py file you're working on? Thank You! 
In the next days I will work on my module before the final merge to enhance some features. Let me know what you think

**Comment by silviapanizzutti** [comment]
Hey guys, first of all great job!, I added the modifications you asked for in your branches on the main.py file.
